/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankmanagement;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Janeesha
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    String date;
    Connection conn;
    double transferAmount, balance;
    int receiverAccNumber, accNumber, accType;

    public transaction() {
    }

    public transaction(int accNumber) {
        initComponents();
        jPanel1.setBackground(new Color(0, 0, 0, 0));
        jTextField1.setBackground(new Color(0, 0, 0, 1));
        jTextField2.setBackground(new Color(0, 0, 0, 1));
        jTextField3.setBackground(new Color(0, 0, 0, 1));
        jTextField4.setBackground(new Color(0, 0, 0, 1));
        jTextField5.setBackground(new Color(0, 0, 0, 1));
        jTextField6.setBackground(new Color(0, 0, 0, 1));
        jTextField7.setBackground(new Color(0, 0, 0, 1));
        jButton1.setBackground(new Color(0, 0, 0, 0));
        jButton2.setBackground(new Color(0, 0, 0, 0));
        conn = dbConfig.getConnection();
        this.accNumber = accNumber;
        startChecker();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1060, 0, 70, 50);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1170, 0, 70, 50);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 100, 290, 30);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 290, 30);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 260, 290, 30);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 310, 290, 30);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 360, 290, 30);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 410, 290, 30);

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 460, 290, 30);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(144, 144, 144));
        jTextField1.setBorder(null);
        jTextField1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(620, 116, 220, 20);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(144, 144, 144));
        jTextField2.setBorder(null);
        jTextField2.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(950, 116, 220, 20);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(144, 144, 144));
        jTextField3.setBorder(null);
        jTextField3.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(620, 162, 220, 20);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(690, 216, 160, 30);

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(700, 334, 160, 30);

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(710, 420, 130, 30);

        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 605, 330, 40);

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 650, 290, 30);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(660, 378, 210, 30);

        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 325, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/transfer.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1250, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1250, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        account log = new account(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        deposit log = new deposit(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        applyLoan log = new applyLoan(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        accStatement log = new accStatement(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        withdraw log = new withdraw(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        billPay log = new billPay(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        payLoan log = new payLoan(accNumber);
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        adminLogin log = new adminLogin();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        homePage log = new homePage();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH-mm-ss");
        LocalDateTime now = LocalDateTime.now();
        date = dtf.format(now);

        if (!(jTextField7.getText().equals(""))) {
            if (validTransferAmount()) {
                try {
                    PreparedStatement pa;

                    String query = "INSERT INTO `accStatement` (`accountNumber` ,`description` ,`referenceNumber` ,`debit` , `credit` , `balance` , `date`) VALUES (?,?,?,?,?,?,?)";
                    pa = conn.prepareStatement(query);
                    pa.setInt(1, receiverAccNumber);
                    pa.setString(2, "transaction");
                    pa.setInt(3, 0);
                    pa.setDouble(4, transferAmount);
                    pa.setDouble(5, 0.0);
                    pa.setDouble(6, balance + transferAmount);
                    pa.setString(7, date);

                    if (pa.executeUpdate() != 0) {
                        enterTransferData();
                    } else {
                        JOptionPane.showMessageDialog(null, "Details aren't successfully recorded", "failed", 2);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "After entering the account number, click on search icon ", "failed", 2);
        }
    }

    private void enterTransferData() {
        try {
            PreparedStatement paa;

            String query = "INSERT INTO `accStatement` (`accountNumber` ,`description` ,`referenceNumber` ,`debit` , `credit` , `balance` , `date`) VALUES (?,?,?,?,?,?,?)";
            paa = conn.prepareStatement(query);
            paa.setInt(1, accNumber);
            paa.setString(2, "transaction");
            paa.setInt(3, 0);
            paa.setDouble(4, 0.0);
            paa.setDouble(5, transferAmount);
            paa.setDouble(6, balance - transferAmount);
            paa.setString(7, date);

            if (paa.executeUpdate() != 0) {
                JOptionPane.showMessageDialog(null, "Your Transaction has been Succfully Performed !");
                clearData();
                getBalance();
            } else {
                JOptionPane.showMessageDialog(null, "Details aren't successfully recorded", "failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validTransferAmount() {
        transferAmount = Double.parseDouble(jTextField6.getText());

        if (jTextField6.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Transferring Amount", "Error", 2);
            return false;
        } else if (!jTextField6.getText().matches("^\\d+\\.\\d+")) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Amount in double format!!!", "Error", 2);
            jTextField6.setText("");
            return false;
        } else if (balance <= transferAmount) {
            JOptionPane.showMessageDialog(null, "Your Current Balance Isn't Enough To Do A Transaction !", "Error", 2);
            return false;
        } else {
            return true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (checkValidAccNumber()) {
            try {
                PreparedStatement pa;
                ResultSet rs;

                String query = "SELECT * FROM `customerlogin` WHERE `accountNumber` = ?";
                pa = conn.prepareStatement(query);
                pa.setInt(1, receiverAccNumber);
                rs = pa.executeQuery();

                accType = Integer.parseInt(rs.getString(7));
                if (accType != 2) {
                    if (rs.next()) {
                        jTextField7.setText(rs.getString(2));
                    } else {
                        JOptionPane.showMessageDialog(null, "This Account Number Doesn't Exist\nTry Again!!!", "Error", 2);
                        jTextField5.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "This Account Number Doesn't Respond To Do Transactions\nTry Again!!!", "Error", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean checkValidAccNumber() {
        if (jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Receiver's Account Number", "Error", 2);
            return false;
        } else if (!jTextField5.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Account Number !!!", "Error", 2);
            jTextField5.setText("");
            return false;
        } else if (jTextField5.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "This Account Number Doesn't Valid !", "Error", 2);
            jTextField5.setText("");
            return false;
        } else {
            receiverAccNumber = Integer.parseInt(jTextField5.getText());
            return true;
        }
    }

    public void startChecker() {
        LocalDate Date = java.time.LocalDate.now();

        jTextField1.setText(Integer.toString(accNumber));
        jTextField2.setText(Date.toString());
        getBalance();

        try {
            PreparedStatement pa;
            ResultSet rs;

            String query = "SELECT * FROM `customerlogin` WHERE `accountNumber` = ?";
            pa = conn.prepareStatement(query);
            pa.setInt(1, accNumber);
            rs = pa.executeQuery();

            if (rs.next()) {
                jTextField3.setText(rs.getString(2));

            }
        } catch (SQLException ex) {
            Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void clearData() {
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
    }

    public void getBalance() {
        calculateBalance c = new calculateBalance(accNumber);
        balance = c.getLastBalance();
        jTextField4.setText(Double.toString(balance));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
