/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankmanagement;

import java.awt.Color;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Janeesha
 */
public class updateBankInfo extends javax.swing.JFrame {

    /**
     * Creates new form updateBankInfo
     */
    Connection conn;
    int rowNo1, rowNo2, rowNo3, rowNo4, rowNo5, num1, num2, num3, num4, num5, timePeriod, id;
    double ir;
    String city, district, contactNumber, salary;

    public updateBankInfo() {
        conn = dbConfig.getConnection();
        initComponents();
        bankInfoMain.setVisible((true));
        personalLoanIr.setVisible((false));
        homeLoanIr.setVisible((false));
        branchDetails.setVisible((false));
        fixedIr.setVisible((false));
        savingsIr.setVisible((false));

        jButton1.setBackground(new Color(0, 0, 0, 0));
        jButton2.setBackground(new Color(0, 0, 0, 0));
        jButton3.setBackground(new Color(0, 0, 0, 0));
        jButton4.setBackground(new Color(0, 0, 0, 0));
        jButton5.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bankInfoMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        personalLoanIr = new javax.swing.JPanel();
        addBtnPersonalLoan = new javax.swing.JButton();
        updateBtnPersonalLoan = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        homeLoanIr = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        updateBtnHomeLoan = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        addBtnHomeLoan = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        savingsIr = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        addBtnSavings = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        updateBtnSavings = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        branchDetails = new javax.swing.JPanel();
        updateBtnBranchDetails = new javax.swing.JButton();
        addBtnBranchDetails = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        fixedIr = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        updateBtnFixed = new javax.swing.JButton();
        addBtnFixed = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        getContentPane().setLayout(null);

        bankInfoMain.setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel2);
        jLabel2.setBounds(10, 110, 300, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel3);
        jLabel3.setBounds(10, 210, 300, 40);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel4);
        jLabel4.setBounds(10, 160, 300, 40);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel5);
        jLabel5.setBounds(10, 320, 300, 40);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel6);
        jLabel6.setBounds(7, 370, 300, 40);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel7);
        jLabel7.setBounds(10, 650, 300, 30);

        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel8);
        jLabel8.setBounds(960, 0, 100, 50);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        bankInfoMain.add(jLabel9);
        jLabel9.setBounds(1150, 0, 90, 50);

        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bankInfoMain.add(jButton1);
        jButton1.setBounds(390, 270, 150, 150);

        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bankInfoMain.add(jButton2);
        jButton2.setBounds(550, 270, 150, 150);

        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bankInfoMain.add(jButton3);
        jButton3.setBounds(710, 270, 150, 150);

        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        bankInfoMain.add(jButton5);
        jButton5.setBounds(1030, 270, 150, 150);

        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bankInfoMain.add(jButton4);
        jButton4.setBounds(870, 270, 150, 150);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/update bank info-page.png"))); // NOI18N
        bankInfoMain.add(jLabel15);
        jLabel15.setBounds(0, 0, 1250, 700);

        getContentPane().add(bankInfoMain);
        bankInfoMain.setBounds(0, 0, 1250, 700);

        personalLoanIr.setLayout(null);

        addBtnPersonalLoan.setBorder(null);
        addBtnPersonalLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnPersonalLoanActionPerformed(evt);
            }
        });
        personalLoanIr.add(addBtnPersonalLoan);
        addBtnPersonalLoan.setBounds(840, 290, 260, 40);

        updateBtnPersonalLoan.setBorder(null);
        updateBtnPersonalLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnPersonalLoanActionPerformed(evt);
            }
        });
        personalLoanIr.add(updateBtnPersonalLoan);
        updateBtnPersonalLoan.setBounds(480, 290, 260, 40);

        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        personalLoanIr.add(jButton7);
        jButton7.setBounds(380, 350, 60, 30);

        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        personalLoanIr.add(jButton6);
        jButton6.setBounds(1130, 200, 50, 40);

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(98, 9, 17));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        personalLoanIr.add(jTextField2);
        jTextField2.setBounds(860, 200, 63, 22);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(98, 9, 17));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        personalLoanIr.add(jTextField1);
        jTextField1.setBounds(800, 165, 210, 22);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time Period (Months)", "Interest Rate (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        personalLoanIr.add(jScrollPane1);
        jScrollPane1.setBounds(660, 380, 300, 270);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/update personal loan.png"))); // NOI18N
        personalLoanIr.add(jLabel10);
        jLabel10.setBounds(0, 0, 1250, 700);

        getContentPane().add(personalLoanIr);
        personalLoanIr.setBounds(0, 0, 1250, 700);

        homeLoanIr.setLayout(null);

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(98, 9, 17));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        homeLoanIr.add(jTextField3);
        jTextField3.setBounds(800, 165, 210, 22);

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(98, 9, 17));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(null);
        homeLoanIr.add(jTextField4);
        jTextField4.setBounds(880, 200, 63, 22);

        updateBtnHomeLoan.setBorder(null);
        updateBtnHomeLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnHomeLoanActionPerformed(evt);
            }
        });
        homeLoanIr.add(updateBtnHomeLoan);
        updateBtnHomeLoan.setBounds(480, 290, 260, 40);

        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        homeLoanIr.add(jButton13);
        jButton13.setBounds(390, 350, 60, 30);

        addBtnHomeLoan.setBorder(null);
        addBtnHomeLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnHomeLoanActionPerformed(evt);
            }
        });
        homeLoanIr.add(addBtnHomeLoan);
        addBtnHomeLoan.setBounds(840, 290, 260, 40);

        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        homeLoanIr.add(jButton12);
        jButton12.setBounds(1130, 200, 50, 40);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time Period (Year)", "Interest Rate  (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setRowHeight(30);
        jTable2.setShowGrid(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        homeLoanIr.add(jScrollPane2);
        jScrollPane2.setBounds(630, 370, 310, 270);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/update home loan ir.png"))); // NOI18N
        homeLoanIr.add(jLabel11);
        jLabel11.setBounds(0, 0, 1250, 700);

        getContentPane().add(homeLoanIr);
        homeLoanIr.setBounds(0, 0, 1250, 700);

        savingsIr.setLayout(null);

        jButton25.setBorder(null);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        savingsIr.add(jButton25);
        jButton25.setBounds(1130, 200, 50, 40);

        addBtnSavings.setBorder(null);
        addBtnSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnSavingsActionPerformed(evt);
            }
        });
        savingsIr.add(addBtnSavings);
        addBtnSavings.setBounds(840, 290, 260, 40);

        jTextField12.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(98, 9, 17));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(null);
        savingsIr.add(jTextField12);
        jTextField12.setBounds(870, 200, 69, 22);

        jTextField11.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(98, 9, 17));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setBorder(null);
        savingsIr.add(jTextField11);
        jTextField11.setBounds(800, 160, 190, 22);

        updateBtnSavings.setBorder(null);
        updateBtnSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnSavingsActionPerformed(evt);
            }
        });
        savingsIr.add(updateBtnSavings);
        updateBtnSavings.setBounds(480, 290, 260, 40);

        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        savingsIr.add(jButton24);
        jButton24.setBounds(380, 350, 60, 40);

        jTable5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Salary Range", "Interest Rate (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setRowHeight(30);
        jTable5.setShowGrid(true);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        savingsIr.add(jScrollPane5);
        jScrollPane5.setBounds(640, 372, 310, 280);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/update savings ir.png"))); // NOI18N
        savingsIr.add(jLabel14);
        jLabel14.setBounds(0, 0, 1250, 700);

        getContentPane().add(savingsIr);
        savingsIr.setBounds(0, 0, 1250, 700);

        branchDetails.setLayout(null);

        updateBtnBranchDetails.setBorder(null);
        updateBtnBranchDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnBranchDetailsActionPerformed(evt);
            }
        });
        branchDetails.add(updateBtnBranchDetails);
        updateBtnBranchDetails.setBounds(460, 340, 270, 40);

        addBtnBranchDetails.setBorder(null);
        addBtnBranchDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnBranchDetailsActionPerformed(evt);
            }
        });
        branchDetails.add(addBtnBranchDetails);
        addBtnBranchDetails.setBounds(850, 330, 270, 40);

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(98, 9, 17));
        jTextField6.setBorder(null);
        branchDetails.add(jTextField6);
        jTextField6.setBounds(760, 202, 310, 22);

        jTextField7.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(98, 9, 17));
        jTextField7.setBorder(null);
        branchDetails.add(jTextField7);
        jTextField7.setBounds(760, 236, 300, 22);

        jButton16.setBorder(null);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        branchDetails.add(jButton16);
        jButton16.setBounds(1130, 280, 60, 30);

        jTextField8.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(98, 9, 17));
        jTextField8.setBorder(null);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        branchDetails.add(jTextField8);
        jTextField8.setBounds(760, 271, 300, 22);

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(98, 9, 17));
        jTextField5.setBorder(null);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        branchDetails.add(jTextField5);
        jTextField5.setBounds(760, 166, 310, 22);

        jButton17.setBorder(null);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        branchDetails.add(jButton17);
        jButton17.setBounds(380, 390, 60, 40);

        jTable4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Branch Id", "City", "District", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setRowHeight(25);
        jTable4.setShowGrid(true);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        branchDetails.add(jScrollPane4);
        jScrollPane4.setBounds(500, 410, 640, 260);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/update bank branch details.png"))); // NOI18N
        branchDetails.add(jLabel12);
        jLabel12.setBounds(0, 0, 1250, 700);

        getContentPane().add(branchDetails);
        branchDetails.setBounds(0, 0, 1250, 700);

        fixedIr.setLayout(null);

        jButton21.setForeground(new java.awt.Color(51, 51, 51));
        jButton21.setBorder(null);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        fixedIr.add(jButton21);
        jButton21.setBounds(390, 350, 50, 40);

        jTextField9.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(98, 9, 17));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });
        fixedIr.add(jTextField9);
        jTextField9.setBounds(802, 162, 190, 22);

        jButton20.setBorder(null);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        fixedIr.add(jButton20);
        jButton20.setBounds(1130, 200, 40, 40);

        updateBtnFixed.setBorder(null);
        updateBtnFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnFixedActionPerformed(evt);
            }
        });
        fixedIr.add(updateBtnFixed);
        updateBtnFixed.setBounds(480, 290, 270, 40);

        addBtnFixed.setBorder(null);
        addBtnFixed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnFixedActionPerformed(evt);
            }
        });
        fixedIr.add(addBtnFixed);
        addBtnFixed.setBounds(840, 290, 260, 40);

        jTextField10.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(98, 9, 17));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(null);
        fixedIr.add(jTextField10);
        jTextField10.setBounds(850, 200, 69, 22);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setColumnHeaderView(null);

        jTable3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time Period (Months)", "Interest Rate (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setRowHeight(30);
        jTable3.setShowGrid(true);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        fixedIr.add(jScrollPane3);
        jScrollPane3.setBounds(630, 380, 340, 270);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system images/update fixed ir.png"))); // NOI18N
        fixedIr.add(jLabel13);
        jLabel13.setBounds(0, 0, 1250, 700);

        getContentPane().add(fixedIr);
        fixedIr.setBounds(0, 0, 1250, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        customerAccounts log = new customerAccounts();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        customerAssets log = new customerAssets();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        loanDetails log = new loanDetails();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        updateMoney log = new updateMoney();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        removeCustomer log = new removeCustomer();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        customerLogin log = new customerLogin();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        homePage log = new homePage();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        personalLoanIr.setVisible((true));
        bankInfoMain.setVisible((false));

        jButton6.setBackground(new Color(0, 0, 0, 0));
        jButton7.setBackground(new Color(0, 0, 0, 0));
        updateBtnPersonalLoan.setBackground(new Color(0, 0, 0, 0));
        addBtnPersonalLoan.setBackground(new Color(0, 0, 0, 0));
        jTextField1.setBackground(new Color(0, 0, 0, 1));
        jTextField2.setBackground(new Color(0, 0, 0, 1));
        addTable1();
        jScrollPane1.getViewport().setBackground(new Color(227, 242, 254));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bankInfoMain.setVisible((false));
        homeLoanIr.setVisible((true));

        updateBtnHomeLoan.setBackground(new Color(0, 0, 0, 0));
        addBtnHomeLoan.setBackground(new Color(0, 0, 0, 0));
        jButton12.setBackground(new Color(0, 0, 0, 0));
        jButton13.setBackground(new Color(0, 0, 0, 0));
        jTextField3.setBackground(new Color(0, 0, 0, 1));
        jTextField4.setBackground(new Color(0, 0, 0, 1));
        addTable2();
        jScrollPane2.getViewport().setBackground(new Color(227, 242, 254));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bankInfoMain.setVisible((false));
        savingsIr.setVisible((true));

        updateBtnSavings.setBackground(new Color(0, 0, 0, 0));
        addBtnSavings.setBackground(new Color(0, 0, 0, 0));
        jButton24.setBackground(new Color(0, 0, 0, 0));
        jButton25.setBackground(new Color(0, 0, 0, 0));
        jTextField11.setBackground(new Color(0, 0, 0, 1));
        jTextField12.setBackground(new Color(0, 0, 0, 1));
        addTable5();
        jScrollPane5.getViewport().setBackground(new Color(227, 242, 254));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bankInfoMain.setVisible((false));
        branchDetails.setVisible((true));

        updateBtnBranchDetails.setBackground(new Color(0, 0, 0, 0));
        addBtnBranchDetails.setBackground(new Color(0, 0, 0, 0));
        jButton16.setBackground(new Color(0, 0, 0, 0));
        jButton17.setBackground(new Color(0, 0, 0, 0));
        jTextField5.setBackground(new Color(0, 0, 0, 1));
        jTextField6.setBackground(new Color(0, 0, 0, 1));
        jTextField7.setBackground(new Color(0, 0, 0, 1));
        jTextField8.setBackground(new Color(0, 0, 0, 1));
        addTable4();
        jScrollPane4.getViewport().setBackground(new Color(227, 242, 254));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        bankInfoMain.setVisible((false));
        fixedIr.setVisible((true));

        updateBtnFixed.setBackground(new Color(0, 0, 0, 0));
        addBtnFixed.setBackground(new Color(0, 0, 0, 0));
        jButton20.setBackground(new Color(0, 0, 0, 0));
        jButton21.setBackground(new Color(0, 0, 0, 0));
        jTextField9.setBackground(new Color(0, 0, 0, 1));
        jTextField10.setBackground(new Color(0, 0, 0, 1));
        addTable3();
        jScrollPane3.getViewport().setBackground(new Color(227, 242, 254));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        resetValue();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        resetValue();
        homeLoanIr.setVisible((false));
        bankInfoMain.setVisible((true));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void updateBtnFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnFixedActionPerformed
        // TODO add your handling code here:
        if (rowNo3 != 0) {
            try {
                PreparedStatement pa;
                ResultSet rs;
                String query = "SELECT * FROM `fixedir` ";
                pa = conn.prepareStatement(query);
                rs = pa.executeQuery();
                int i = 0;
                while (rs.next()) {
                    i++;
                    if (i == rowNo3) {
                        num3 = Integer.parseInt(rs.getString(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (checkValidFixedIrDetail()) {
                try {
                    PreparedStatement paa;
                    String query = "UPDATE `fixedir` SET `duration` = ? ,`interestRate` = ? WHERE `number` = ?";
                    paa = conn.prepareStatement(query);
                    paa.setInt(1, timePeriod);
                    paa.setDouble(2, ir);
                    paa.setInt(3, num3);
                    if (paa.executeUpdate() != 0) {
                        addTable3();
                        resetValue();
                        JOptionPane.showMessageDialog(null, "Details habe been successfully updated");
                    } else {
                        JOptionPane.showMessageDialog(null, "Upadate Unsuccessful ", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "First Select a Row in the following Table", "failed", 2);
        }
    }//GEN-LAST:event_updateBtnFixedActionPerformed

    private void addBtnFixedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnFixedActionPerformed
        // TODO add your handling code here:
        if (checkValidFixedIrDetail()) {
            try {
                PreparedStatement paa;

                String query = "INSERT INTO `fixedir` (`duration` ,`interestRate` ) VALUES (?,?)";
                paa = conn.prepareStatement(query);
                paa.setInt(1, timePeriod);
                paa.setDouble(2, ir);
                if (paa.executeUpdate() != 0) {
                    addTable3();
                    resetValue();
                    JOptionPane.showMessageDialog(null, "Details added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Details aren't successfully added", "failed", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addBtnFixedActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        resetValue();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        resetValue();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        resetValue();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        resetValue();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        resetValue();
        personalLoanIr.setVisible((false));
        bankInfoMain.setVisible((true));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        resetValue();
        branchDetails.setVisible((false));
        bankInfoMain.setVisible((true));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        resetValue();
        savingsIr.setVisible((false));
        bankInfoMain.setVisible((true));
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        resetValue();
        fixedIr.setVisible((false));
        bankInfoMain.setVisible((true));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void updateBtnPersonalLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnPersonalLoanActionPerformed
        // TODO add your handling code here:
        if (rowNo1 != 0) {
            try {
                PreparedStatement pa;
                ResultSet rs;
                String query = "SELECT * FROM `personalloanir` ";
                pa = conn.prepareStatement(query);
                rs = pa.executeQuery();
                int i = 0;
                while (rs.next()) {
                    i++;
                    if (i == rowNo1) {
                        num1 = Integer.parseInt(rs.getString(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (checkValidPersonalLoanDetail()) {
                try {
                    PreparedStatement paa;
                    String query = "UPDATE `personalloanir` SET `duration` = ? ,`interestRate` = ? WHERE `number` = ?";
                    paa = conn.prepareStatement(query);
                    paa.setInt(1, timePeriod);
                    paa.setDouble(2, ir);
                    paa.setInt(3, num1);
                    if (paa.executeUpdate() != 0) {
                        addTable1();
                        resetValue();
                        JOptionPane.showMessageDialog(null, "Details habe been successfully updated");
                    } else {
                        JOptionPane.showMessageDialog(null, "Upadate Unsuccessful ", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "First Select a Row in the following Table", "failed", 2);
        }
    }//GEN-LAST:event_updateBtnPersonalLoanActionPerformed

    private void addBtnPersonalLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnPersonalLoanActionPerformed
        // TODO add your handling code here:
        if (checkValidPersonalLoanDetail()) {
            try {
                PreparedStatement paa;

                String query = "INSERT INTO `personalloanir` (`duration` ,`interestRate` ) VALUES (?,?)";
                paa = conn.prepareStatement(query);
                paa.setInt(1, timePeriod);
                paa.setDouble(2, ir);
                if (paa.executeUpdate() != 0) {
                    addTable1();
                    resetValue();
                    JOptionPane.showMessageDialog(null, "Details added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Details aren't successfully added", "failed", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addBtnPersonalLoanActionPerformed

    private void updateBtnHomeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnHomeLoanActionPerformed
        // TODO add your handling code here:
        if (rowNo2 != 0) {
            try {
                PreparedStatement pa;
                ResultSet rs;
                String query = "SELECT * FROM `homeloanir` ";
                pa = conn.prepareStatement(query);
                rs = pa.executeQuery();
                int i = 0;
                while (rs.next()) {
                    i++;
                    if (i == rowNo2) {
                        num2 = Integer.parseInt(rs.getString(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (checkValidHomeLoanDetail()) {
                try {
                    PreparedStatement paa;
                    String query = "UPDATE `homeloanir` SET `duration` = ? ,`interestRate` = ? WHERE `number` = ?";
                    paa = conn.prepareStatement(query);
                    paa.setInt(1, timePeriod);
                    paa.setDouble(2, ir);
                    paa.setInt(3, num2);
                    if (paa.executeUpdate() != 0) {
                        addTable2();
                        resetValue();
                        JOptionPane.showMessageDialog(null, "Details habe been successfully updated");
                    } else {
                        JOptionPane.showMessageDialog(null, "Upadate Unsuccessful ", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "First Select a Row in the following Table", "failed", 2);
        }
    }//GEN-LAST:event_updateBtnHomeLoanActionPerformed

    private void addBtnHomeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnHomeLoanActionPerformed
        // TODO add your handling code here:
        if (checkValidHomeLoanDetail()) {
            try {
                PreparedStatement paa;

                String query = "INSERT INTO `homeloanir` (`duration` ,`interestRate` ) VALUES (?,?)";
                paa = conn.prepareStatement(query);
                paa.setInt(1, timePeriod);
                paa.setDouble(2, ir);
                if (paa.executeUpdate() != 0) {
                    addTable2();
                    resetValue();
                    JOptionPane.showMessageDialog(null, "Details added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Details aren't successfully added", "failed", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addBtnHomeLoanActionPerformed

    private void addBtnSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnSavingsActionPerformed
        // TODO add your handling code here:
        if (checkValidSavingIrDetail()) {
            try {
                PreparedStatement paa;

                String query = "INSERT INTO savingir` (`salary` ,`interestRate` ) VALUES (?,?)";
                paa = conn.prepareStatement(query);
                paa.setString(1, salary);
                paa.setDouble(2, ir);
                if (paa.executeUpdate() != 0) {
                    addTable5();
                    resetValue();
                    JOptionPane.showMessageDialog(null, "Details added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Details aren't successfully added", "failed", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_addBtnSavingsActionPerformed

    private void updateBtnSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnSavingsActionPerformed
        // TODO add your handling code here:
        if (rowNo5 != 0) {
            try {
                PreparedStatement pa;
                ResultSet rs;
                String query = "SELECT * FROM `savingir` ";
                pa = conn.prepareStatement(query);
                rs = pa.executeQuery();
                int i = 0;
                while (rs.next()) {
                    i++;
                    if (i == rowNo5) {
                        num5 = Integer.parseInt(rs.getString(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (checkValidSavingIrDetail()) {
                try {
                    PreparedStatement paa;
                    String query = "UPDATE `savingir` SET `salary` = ? ,`interestRate` = ? WHERE `number` = ?";
                    paa = conn.prepareStatement(query);
                    paa.setString(1, salary);
                    paa.setDouble(2, ir);
                    paa.setInt(3, num5);
                    if (paa.executeUpdate() != 0) {
                        addTable5();
                        resetValue();
                        JOptionPane.showMessageDialog(null, "Details habe been successfully updated");
                    } else {
                        JOptionPane.showMessageDialog(null, "Upadate Unsuccessful ", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "First Select a Row in the following Table", "failed", 2);
        }
    }//GEN-LAST:event_updateBtnSavingsActionPerformed

    private void updateBtnBranchDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnBranchDetailsActionPerformed
        // TODO add your handling code here:
        if (rowNo4 != 0) {
            try {
                PreparedStatement pa;
                ResultSet rs;
                String query = "SELECT * FROM `branches` ";
                pa = conn.prepareStatement(query);
                rs = pa.executeQuery();
                int i = 0;
                while (rs.next()) {
                    i++;
                    if (i == rowNo4) {
                        num4 = Integer.parseInt(rs.getString(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (checkValidBranchDetail()) {
                try {
                    PreparedStatement paa;
                    String query = "UPDATE `branches` SET `id` = ?,`city` = ?, `district` = ?,`contactNumber` = ? WHERE `number` = ?";
                    paa = conn.prepareStatement(query);
                    paa.setInt(1, id);
                    paa.setString(2, city);
                    paa.setString(3, district);
                    paa.setString(4, contactNumber);
                    paa.setInt(5, num4);
                    if (paa.executeUpdate() != 0) {
                        addTable4();
                        resetValue();
                        JOptionPane.showMessageDialog(null, "Details habe been successfully updated");
                    } else {
                        JOptionPane.showMessageDialog(null, "Upadate Unsuccessful ", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "First Select a Row in the following Table", "failed", 2);
        }
    }//GEN-LAST:event_updateBtnBranchDetailsActionPerformed

    private void addBtnBranchDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnBranchDetailsActionPerformed
        // TODO add your handling code here:
        if (checkValidBranchDetail()) {
            try {
                PreparedStatement paa;

                String query = "INSERT INTO `branches` (`id` ,`city` , `district` ,`contactNumber` ) VALUES (?,?,?,?)";
                paa = conn.prepareStatement(query);
                paa.setInt(1, id);
                paa.setString(2, city);
                paa.setString(3, district);
                paa.setString(4, contactNumber);
                if (paa.executeUpdate() != 0) {
                    addTable4();
                    resetValue();
                    JOptionPane.showMessageDialog(null, "Details added Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Details aren't successfully added", "failed", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(updateBankInfo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_addBtnBranchDetailsActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        rowNo1 = jTable1.getSelectedRow() + 1;
        try {
            PreparedStatement pa;
            ResultSet rs;

            String query = "SELECT * FROM `personalloanir` ";
            pa = conn.prepareStatement(query);
            rs = pa.executeQuery();

            int i = 0;
            while (rs.next()) {
                i++;
                if (i == rowNo1) {
                    jTextField1.setText(rs.getString(2));
                    jTextField2.setText(rs.getString(3));

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        rowNo2 = jTable2.getSelectedRow() + 1;
        try {
            PreparedStatement pa;
            ResultSet rs;

            String query = "SELECT * FROM `homeloanir` ";
            pa = conn.prepareStatement(query);
            rs = pa.executeQuery();

            int i = 0;
            while (rs.next()) {
                i++;
                if (i == rowNo2) {
                    jTextField3.setText(rs.getString(2));
                    jTextField4.setText(rs.getString(3));

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        rowNo5 = jTable5.getSelectedRow() + 1;
        try {
            PreparedStatement pa;
            ResultSet rs;

            String query = "SELECT * FROM `savingir` ";
            pa = conn.prepareStatement(query);
            rs = pa.executeQuery();

            int i = 0;
            while (rs.next()) {
                i++;
                if (i == rowNo5) {
                    jTextField11.setText(rs.getString(2));
                    jTextField12.setText(rs.getString(3));

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        rowNo4 = jTable4.getSelectedRow() + 1;
        try {
            PreparedStatement pa;
            ResultSet rs;

            String query = "SELECT * FROM `branches` ";
            pa = conn.prepareStatement(query);
            rs = pa.executeQuery();

            int i = 0;
            while (rs.next()) {
                i++;
                if (i == rowNo4) {
                    jTextField5.setText(rs.getString(2));
                    jTextField6.setText(rs.getString(3));
                    jTextField7.setText(rs.getString(4));
                    jTextField8.setText(rs.getString(5));

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        rowNo3 = jTable3.getSelectedRow() + 1;
        try {
            PreparedStatement pa;
            ResultSet rs;

            String query = "SELECT * FROM `fixedir` ";
            pa = conn.prepareStatement(query);
            rs = pa.executeQuery();

            int i = 0;
            while (rs.next()) {
                i++;
                if (i == rowNo3) {
                    jTextField9.setText(rs.getString(2));
                    jTextField10.setText(rs.getString(3));

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyTyped

    public void resetValue() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
    }

    public void addTable1() {
        PreparedStatement pa;
        ResultSet rs;

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        String sql = "SELECT * FROM `personalloanir`";
        try {
            pa = conn.prepareStatement(sql);
            rs = pa.executeQuery();
            model = (DefaultTableModel) jTable1.getModel();

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(2), rs.getString(3)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addTable2() {
        PreparedStatement pa;
        ResultSet rs;

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        String sql = "SELECT * FROM `homeloanir`";
        try {
            pa = conn.prepareStatement(sql);
            rs = pa.executeQuery();
            model = (DefaultTableModel) jTable2.getModel();

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(2), rs.getString(3)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addTable3() {
        PreparedStatement pa;
        ResultSet rs;

        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        String sql = "SELECT * FROM `fixedir`";
        try {
            pa = conn.prepareStatement(sql);
            rs = pa.executeQuery();
            model = (DefaultTableModel) jTable3.getModel();

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(2), rs.getString(3)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addTable4() {
        PreparedStatement pa;
        ResultSet rs;

        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);
        String sql = "SELECT * FROM `branches`";
        try {
            pa = conn.prepareStatement(sql);
            rs = pa.executeQuery();
            model = (DefaultTableModel) jTable4.getModel();

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addTable5() {
        PreparedStatement pa;
        ResultSet rs;

        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);
        String sql = "SELECT * FROM `savingir`";
        try {
            pa = conn.prepareStatement(sql);
            rs = pa.executeQuery();
            model = (DefaultTableModel) jTable5.getModel();

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(2), rs.getString(3)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(updateBankInfo.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean checkValidPersonalLoanDetail() {
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter a Time Period .", "failed", 2);
            return false;
        } else {
            timePeriod = Integer.parseInt(jTextField1.getText());
            if (jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter an Interest Rate .", "failed", 2);
                return false;
            } else {
                if (jTextField2.getText().matches("^\\d+\\.\\d+")) {
                    ir = Double.parseDouble(jTextField2.getText());
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Please Enter a Valid Interest Rate in double format!!!", "Error", 2);
                    jTextField2.setText("");
                    return false;
                }
            }
        }
    }

    public boolean checkValidHomeLoanDetail() {
        if (jTextField3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter a Time Period .", "failed", 2);
            return false;
        } else {
            timePeriod = Integer.parseInt(jTextField3.getText());
            if (jTextField4.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter an Interest Rate .", "failed", 2);
                return false;
            } else {
                if (jTextField4.getText().matches("^\\d+\\.\\d+")) {
                    ir = Double.parseDouble(jTextField4.getText());
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Please Enter a Valid Interest Rate in double format!!!", "Error", 2);
                    jTextField4.setText("");
                    return false;
                }
            }
        }
    }

    public boolean checkValidSavingIrDetail() {
        if (jTextField11.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter a Salary Range .", "failed", 2);
            return false;
        } else if (jTextField12.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter an Interest Rate .", "failed", 2);
            return false;
        } else if (jTextField12.getText().matches("^\\d+\\.\\d+")) {
            salary = jTextField11.getText();
            ir = Double.parseDouble(jTextField12.getText());
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Please Enter a Valid Interest Rate in double format!!!", "Error", 2);
            jTextField11.setText("");
            jTextField12.setText("");
            return false;
        }
    }

    public boolean checkValidBranchDetail() {
        if (jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Branch Id Number .", "failed", 2);
            return false;
        } else {
            id = Integer.parseInt(jTextField5.getText());
            if (jTextField6.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter Name Of City .", "failed", 2);
                return false;
            } else {
                city = jTextField6.getText();
                if (jTextField7.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Please Enter Name Of District .", "failed", 2);
                    return false;
                } else {
                    district = jTextField7.getText();
                    if (jTextField8.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Please Enter Contact Number .", "failed", 2);
                        return false;
                    } else {
                        contactNumber = jTextField8.getText();
                        return true;
                    }
                }
            }
        }
    }

    public boolean checkValidFixedIrDetail() {
        if (jTextField9.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter a Time Period .", "failed", 2);
            return false;
        } else {
            timePeriod = Integer.parseInt(jTextField9.getText());
            if (jTextField10.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter an Interest Rate .", "failed", 2);
                return false;
            } else {
                if (jTextField10.getText().matches("^\\d+\\.\\d+")) {
                    ir = Double.parseDouble(jTextField10.getText());
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "Please Enter a Valid Interest Rate in double format!!!", "Error", 2);
                    jTextField10.setText("");
                    return false;
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateBankInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateBankInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateBankInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateBankInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateBankInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtnBranchDetails;
    private javax.swing.JButton addBtnFixed;
    private javax.swing.JButton addBtnHomeLoan;
    private javax.swing.JButton addBtnPersonalLoan;
    private javax.swing.JButton addBtnSavings;
    private javax.swing.JPanel bankInfoMain;
    private javax.swing.JPanel branchDetails;
    private javax.swing.JPanel fixedIr;
    private javax.swing.JPanel homeLoanIr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel personalLoanIr;
    private javax.swing.JPanel savingsIr;
    private javax.swing.JButton updateBtnBranchDetails;
    private javax.swing.JButton updateBtnFixed;
    private javax.swing.JButton updateBtnHomeLoan;
    private javax.swing.JButton updateBtnPersonalLoan;
    private javax.swing.JButton updateBtnSavings;
    // End of variables declaration//GEN-END:variables
}
